### ISSUE TITLE
Issue with libcloud

### ISSUE THREAD

**Issue by fredmunster** [bernard357/plumbery#2]
Hi,

there is a problem if using the current version of libcloud installed by 

apt-get install libcloud.

Problem was solved by uninstalling libcloud: 

apt-get remove libcloud

then using last version from github

git clone https://github.com/apache/libcloud

then changing the path to the new libcloud folder

export PYTHONPATH=/xxx/xxx/libcloud:$PYTHONPATH
 

Problem description
 
root@10-0-0-10:/Users/fmunster/plumbery/demos# python build_all_blueprints.py
Building all blueprints
Plumbing at 'EU7' Europe _ Amsterdam (Netherlands)
Building blueprint 'control'
Creating network domain 'VDC3'
- in progress
Traceback (most recent call last):
  File "build_all_blueprints.py", line 3, in <module>
    PlumberyEngine('fittings.yaml').build_all_blueprints()
  File "/Users/fmunster/plumbery/plumbery/engine.py", line 163, in build_all_blueprints
    facility.build_all_blueprints()
  File "/Users/fmunster/plumbery/plumbery/facility.py", line 90, in build_all_blueprints
    self.build_blueprint(blueprint.keys()[0])
  File "/Users/fmunster/plumbery/plumbery/facility.py", line 106, in build_blueprint
    domain.build(blueprint)
  File "/Users/fmunster/plumbery/plumbery/domain.py", line 134, in build
    "Error: unable to create network domain '{0}' {1}!".format(domainName, feedback))
plumbery.exceptions.PlumberyException: Error: unable to create network domain 'VDC3' 'DimensionDataNodeDriver' object has no attribute 'ex_wait_for_state'!
 
 
 
 
fittings.yaml
 
---
# fittings to be deployed, managed, and destroyed in the cloud infrastructure of Dimension Data
 
# in safe mode no change is actually made on the infrastructure
safeMode: False
 
#
polishers:
  - ansible:
      reap: test_inventory.yaml
  - rub:
      key: ~/.ssh/id_rsa.pub
      reap: test_rubs.yaml
  - spit:
      reap: test_nodes.yaml
 
# each facility is described separately
---
# Amsterdam in Europe - 10.2.x.y
locationId: EU7
regionId: dd-eu
 
blueprints:
 
  # management, administration, and monitoring
  - control:
      domain: &vdc2
        name: VDC3
        description: '#vdc2'
      ethernet:
        name: control
        subnet: 10.2.10.0
        description: '#vdc2'
      nodes:
        - stackstorm2:
            description: 'StackStorm engine #vdc2 #ops'
            appliance: 'RedHat 6 64-bit 4 CPU'
        - zabbix2:
            description: 'Zabbix dashboard #vdc2 #ops'
            appliance: 'RedHat 6 64-bit 2 CPU'
        - scom1:
            appliance: 'Win2012 R2 Std 4 CPU'
            description: 'Microsoft System Center Operation Manager #vdc2 #ops'
        - scom2:
            appliance: 'Win2012 R2 Std 4 CPU'
            description: 'Microsoft System Center Operation Manager #vdc2 #ops'
 
  # workloads dealing directly with end-user devices
  - web:
      domain: *vdc2
      ethernet: &prod
        name: production
        subnet: 10.2.2.0
        description: '#vdc2'
      nodes:
        - web1:
            description: 'Stateless web #vdc2 #primary'
        - web2:
            description: 'Stateless web #vdc2 #primary'
        - web3:
            description: 'Stateless web #vdc2 #primary'
        - web4:
            description: 'Stateless web #vdc2 #primary'
        - web5:
            description: 'Stateless web #vdc2 #primary'
 
  # workloads dealing with short-term memory
  - memcache:
      domain: *vdc2
      ethernet: *prod
      nodes:
        - redis1:
            description: 'Redis #vdc2 #primary'
        - redis2:
            description: 'Redis #vdc2 #primary'
 
  # workloads dedicated to data records
  - sql:
      domain: *vdc2
      ethernet: &data
        name: data
        subnet: 10.2.3.0
        description: '#vdc2'
      nodes:
        - masterSQL:
            description: 'SQL #vdc2 #primary'
            appliance: 'RedHat 6 64-bit 4 CPU'
 
  # workloads dedicated to big data
  - cassandra:
      domain: *vdc2
      ethernet: *data
      nodes:
        - cassandra1:
            description: 'Cassandra #vdc2 #primary'
        - cassandra2:
            description: 'Cassandra #vdc2 #primary'
        - cassandra3:
            description: 'Cassandra #vdc2 #primary'
 
  # workloads dedicated to BLOBs
  - mongodb:
      domain: *vdc2
      ethernet: *data
      nodes:
        - mongo1:
            description: 'MongoDB #vdc2 #primary'
        - mongo2:
            description: 'MongoDB #vdc2 #primary'
        - mongo3:
            description: 'MongoDB #vdc2 #primary'
 
  # workloads devoted to object-based storage
  - s3:
      domain: *vdc2
      ethernet: *data
      nodes:
        - ceph1:
            description: 'Ceph #vdc2 #primary'
        - ceph2:
            description: 'Ceph #vdc2 #primary'
        - ceph3:
            description: 'Ceph #vdc2 #primary'
 
  # workloads dedicated to source code and related
  - source:
      domain: *vdc2
      ethernet:
        name: source
        subnet: 10.0.4.0
        description: '#vdc2'
      nodes:
        - gitlab:
            description: 'GitLab #vdc2 #dev'
 
# some network domains may have been created manually - they are considered part of these fittings
domains:
 
# some nodes may have been created manually - they are considered part of these fittings
nodes:

**Comment by fxcasadei** [comment]
Hello,
You can also create the domain first, using the "basement" statement in your fittings.yaml file.
So the new 'ex_wait_for_state' method will not be called.

locationId: EU7
regionId: dd-eu
basement: control
blueprints:
# management, administration, and monitoring
control:
...

**Comment by bernard357** [comment]
Thanks Fred. As you described it, the member function 'ex_wait_for_state' is absent from the libcloud python package, and can be used only from the the git clone of libcloud. A new version of plumbery 0.2.2 has been released that does not use 'ex_wait_for_state'. Please use `pip install plumbery --upgrade` to move to version 0.2.2.

**Comment by bernard357** [comment]
Normally now there is no need to install libcloud separately from plumbery. As per [new instructions to get started](https://plumbery.readthedocs.org/en/latest/getting_started.html) you can rely on the python packagers to make it work correctly. The full install and validation has been validated on a fresh Ubuntu machine.
